version: "3"
services:
  api:
    build: .
    restart: always
    depends_on:
      - mongo
  mongo:
    build: db
    restart: always
  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

