version: "3"
services:
  api:
    build: .
    restart: always
    depends_on:
      - mongo
  mongo:
    build: db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: correcthorsebatterystaple
  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

